version: "3.2"

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    image: gateway
    container_name: gateway
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=influxdb
      - DB_USER=admin
      - DB_NAME=data
      - DB_PASS=admin
    networks:
      - default

networks:
  default:
    external:
      name: docker-tig_docker-tig