version: "3.2"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: always
    volumes:
      - /sys/class/thermal:/sys/class/thermal
    environment:
      - DB_HOST:'localhost'
      - DB_USER:'admin'
      - DB_PASS:'admin'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge